workflows:
  ios-release-build:
    name: iOS Release Build (unsigned)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/.pub-cache
        - ios/Pods

    scripts:
      - name: Flutter doctor + pub get + precache iOS
        script: |
          set -euo pipefail
          flutter doctor -v
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Ensure iOS 13 + Swift 5 (patch Podfile safely, no heredoc)
        script: |
          set -euo pipefail
          # ارفع الحد الأدنى لـ iOS
          /usr/bin/sed -i '' "s/^platform :ios.*/platform :ios, '13.0'/" ios/Podfile || true

          # لو post_install غير موجود، أضِفه بسطر-بسطر عبر printf (بدون heredoc)
          if ! grep -q "post_install do |installer|" ios/Podfile; then
            {
              printf "%s\n" "post_install do |installer|"
              printf "%s\n" "  installer.pods_project.targets.each do |t|"
              printf "%s\n" "    t.build_configurations.each do |bc|"
              printf "%s\n" "      bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'"
              printf "%s\n" "      bc.build_settings['SWIFT_VERSION'] = '5.0'"
              printf "%s\n" "    end"
              printf "%s\n" "  end"
              printf "%s\n" "end"
            } >> ios/Podfile
          fi

      - name: CocoaPods (clean install)
        script: |
          set -euo pipefail
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Flutter build iOS (no codesign)
        script: |
          set -euo pipefail
          flutter build ios --release --no-codesign -v

      - name: Package unsigned IPA
        script: |
          set -euo pipefail
          APP_PATH="build/ios/iphoneos/Runner.app"
          OUT_DIR="build/ios/ipa"
          rm -rf "$OUT_DIR"
          mkdir -p "$OUT_DIR/Payload"
          cp -R "$APP_PATH" "$OUT_DIR/Payload/Runner.app"
          (cd "$OUT_DIR" && zip -r -y Runner-unsigned.ipa Payload)

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/Runner-unsigned.ipa
